import type { Config } from 'tailwindcss';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdcc0',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#004b73',
        'secondary-container': '#dae2fd',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-container-highest': '#e0e3e5',
        'surface': '#f7f9fb',
        'secondary-fixed-dim': '#bec6e0',
        'tertiary': '#894d00',
        'primary': '#006194',
        'primary-fixed': '#cce5ff',
        'inverse-on-surface': '#eff1f3',
        'background': '#f7f9fb',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#2d1600',
        'on-surface': '#191c1e',
        'surface-tint': '#006398',
        'primary-container': '#007bb9',
        'surface-bright': '#f7f9fb',
        'error': '#ba1a1a',
        'tertiary-container': '#ac6200',
        'on-surface-variant': '#3f4850',
        'surface-variant': '#e0e3e5',
        'on-primary-container': '#fdfcff',
        'surface-container-high': '#e6e8ea',
        'primary-fixed-dim': '#93ccff',
        'on-secondary-fixed': '#131b2e',
        'on-primary-fixed': '#001d31',
        'surface-container': '#eceef0',
        'on-background': '#191c1e',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#6b3b00',
        'outline-variant': '#bfc7d2',
        'outline': '#707881',
        'secondary': '#565e74',
        'on-secondary-container': '#5c647a',
        'inverse-primary': '#93ccff',
        'secondary-fixed': '#dae2fd',
        'inverse-surface': '#2d3133',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'xxl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'base': '8px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'margin': '32px',
      },
      fontFamily: {
        'label-bold': ['Manrope'],
        'body-base': ['Manrope'],
        'body-sm': ['Manrope'],
        'display-lg': ['Manrope'],
        'headline-md': ['Manrope'],
      },
      fontSize: {
        'label-bold': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-base': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      boxShadow: {
        'sm': '0 1px 3px rgba(0, 0, 0, 0.1)',
        'md': '0 4px 6px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
} satisfies Config;
